### ISSUE TITLE
Dead links in README.md

### ISSUE THREAD

**Issue by balQu** [SebastianBecker2/VideoDedup#7]
There are two dead links at the very bottom of [README.md](https://github.com/SebastianBecker2/VideoDedup/blob/master/README.md)

> For detailed configuration check [x64 libmpv_build_config](https://github.com/SebastianBecker2/VideoDedup/blob/master/VideoDedupShared/Libs/libmpv/x64/libmpv_build_config) and [x86 libmpv_build_config](https://github.com/SebastianBecker2/VideoDedup/blob/master/VideoDedupShared/Libs/libmpv/x86/libmpv_build_config) respectively.

**Comment by SebastianBecker2** [comment]
Fixed.
Updated libmpv to 0.33.1 and added the build_config files for both platforms respectively.
